# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-beta
kind: Project
metadata:
  id: brigade-noisy-neighbor
description: Noisy neighbor for Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/brigade-noisy-neighbor
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
    - push
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/brigade-noisy-neighbor.git
